name: Deploy Node.js app to AWS EC2

on:
  push:
    branches:
      - main  # Adjust the branch name based on your setup

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

    - name: Deploy to EC2
      run: |
        # SSH into EC2 instance and deploy app
        ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          # Navigate to your app directory on the EC2 instance
          cd /path/to/your/app || { echo "App directory not found!"; exit 1; }

          # Pull the latest code from GitHub
          git fetch origin
          git checkout main
          git pull origin main

          # Install the latest dependencies
          npm install

          # (Optional) If you need to build your app, uncomment this line
          # npm run build

          # Restart the app using PM2 (or any other process manager you're using)
          pm2 restart app || pm2 start app.js --name app

          # Optionally, save the PM2 process list
          pm2 save

        EOF
      env:
        AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
        AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
